import Head from "next/head";

// icons
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";

import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amol Shelke Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* main section */}
      <main className=" bg-white px-10">
        <section className="min-h-screen">
          {/* nav section */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">AmolShelke</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4  py-2 rounded-md ml-8">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {/* hero section */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Amol Shelke
            </h2>
            <h3 className="text-2xl py-2">Developer and Designer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Self-tought web developer providing services for programming
              needs. Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <AiFillLinkedin className=" cursor-pointer" />
            <AiFillTwitterCircle className=" cursor-pointer" />
            <AiFillInstagram className=" cursor-pointer" />
          </div>
          <div className="relative bg-gradient-to-b mx-auto from-teal-500 rounded-full w-80 h-80 my-10 overflow-hidden">
            <Image
              alt="hero image"
              src={deved}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a self-tought developer, I've
              created so many projects And shared it on
              <span className="text-teal-500">Linkedin</span> and share the code
              on <span className="text-teal-500">Github</span>. I'm always
              looking for some challenging projects to work on.
            </p>
          </div>

          {/* card section */}
        </section>
      </main>
    </div>
  );
}
