import Head from 'next/head';

// icons
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from 'react-icons/ai';

import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';

import code from '../public/code.png';
import consulting from '../public/consulting.png';
import design from '../public/design.png';

import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amol Shelke Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* main section */}
      <main className=" bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          {/* nav section */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">AmolShelke</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4  py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {/* hero section */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Amol Shelke
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              Self-tought web developer providing services for programming
              needs. Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <AiFillLinkedin className=" cursor-pointer" />
            <AiFillTwitterCircle className=" cursor-pointer" />
            <AiFillInstagram className=" cursor-pointer" />
          </div>
          <div className="relative bg-gradient-to-b mx-auto from-teal-500 rounded-full w-80 h-80 my-10 overflow-hidden md:h-96 md:w-96">
            <Image
              alt="hero image"
              src={deved}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        <section className="my-2">
          <div className="flex flex-col items-center justify-center lg:max-w-xl mx-auto">
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a self-tought developer, I've
              created so many projects And shared it on
              <span className="text-teal-500"> Linkedin</span> and share the
              code on <span className="text-teal-500">Github</span>. I'm always
              looking for some challenging projects to work on.
            </p>
          </div>

          {/* card section */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex flex-col items-center justify-center">
              <Image src={design} alt="design" height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following design
                core theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex flex-col items-center justify-center">
              <Image src={code} alt="code" height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Web devlopment</h3>
              <p className="py-2">
                Converting designs in code with the experince which from my
                personal projects.
              </p>
              <h4 className="py-4 text-teal-600">Specialize in following</h4>
              <p className="text-gray-800 py-1">Front-end Development</p>
              <p className="text-gray-800 py-1">HTML CSS and JavaScript</p>
              <p className="text-gray-800 py-1">ReactJS</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex flex-col items-center justify-center">
              <Image
                src={consulting}
                alt="consulting"
                height={100}
                width={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">
                Consulting my batchmates regarding web and app development. And
                Open-source
              </p>
              <h4 className="py-4 text-teal-600">Consulting in following</h4>
              <p className="text-gray-800 py-1">Web development</p>
              <p className="text-gray-800 py-1">Open-source</p>
              <p className="text-gray-800 py-1">Technical writing</p>
            </div>
          </div>
        </section>

        <section className=" my-10">
          <div className="lg:max-w-xl mx-auto">
            <h3 className="text-3xl py-1">Project</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a self-tought developer, I've
              created so many projects And shared it on
              <span className="text-teal-500">Linkedin</span> and share the code
              on <span className="text-teal-500">Github</span>. I'm always
              looking for some challenging projects to work on.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                src={web1}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                src={web2}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                src={web3}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                src={web4}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                src={web5}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                src={web6}
                alt=""
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
